
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/sitemap-patologias.xml"
  to = "https://igulwzwituvozwneguky.supabase.co/functions/v1/generate-sitemaps"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/sitemap-reviews.xml"
  to = "https://igulwzwituvozwneguky.supabase.co/functions/v1/generate-reviews-sitemap"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
