
project_id = "igulwzwituvozwneguky"

[api]
enabled = true
url = "https://igulwzwituvozwneguky.supabase.co"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndWx3endpdHV2b3p3bmVndWt5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjMzMTAzNCwiZXhwIjoyMDUxOTA3MDM0fQ.uvdDS20jw_Y_EXiHE_24QeHHRcH7DIzGLJ2ZQ8ssJFM"

[functions.generate-reviews-sitemap]
verify_jwt = false
