name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Debug Environment
        run: |
          echo "Checking Supabase configuration..."
          if [ -n "${{ secrets.SUPABASE_URL }}" ]; then
            echo "SUPABASE_URL is set"
          else
            echo "SUPABASE_URL is not set"
          fi
          if [ -n "${{ secrets.SUPABASE_ANON_KEY }}" ]; then
            echo "SUPABASE_ANON_KEY is set"
          else
            echo "SUPABASE_ANON_KEY is not set"
          fi
        
      - name: Generate sitemap
        run: node scripts/generateSitemaps.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
      - name: Debug Git Status
        run: |
          git status
          ls -la public/
          
      - name: Commit and push sitemap
        run: |
          git add public/sitemap*.xml
          git status
          git diff --staged --quiet || (git commit -m "Update sitemap [skip ci]" && git push)